{% set name = "shiv" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shiv-{{ version }}.tar.gz
  sha256: bf146ff3f3abca2eb1214e86018f36124a1c22d93540eef5240321cacd7d7f57

build:
  noarch: python
  entry_points:
    - shiv = shiv.cli:main
    - shiv-info = shiv.info:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click !=7.0,>=6.7
    - importlib-resources
    - pip >=9.0.3
    - python >=3.6
    - setuptools

test:
  imports:
    - shiv
  commands:
    - pip check
    - shiv --help
    - shiv-info --help
  requires:
    - pip

about:
  home: https://github.com/linkedin/shiv
  doc_url: https://shiv.readthedocs.io/en/latest/
  summary: A command line utility for building fully self contained Python zipapps.
  license: BSD-2-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
