{% set name = "shiv" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shiv-{{ version }}.tar.gz
  sha256: 2a68d69e98ce81cb5b8fdafbfc1e27efa93e6d89ca14bfae33482e4176f561d6

build:
  noarch: python
  entry_points:
    - shiv = shiv.cli:main
    - shiv-info = shiv.info:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip >=9.0.3
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - click !=7.0,>=6.7
    - importlib-resources
    - pip >=9.0.3
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - shiv
  commands:
    - pip check
    - shiv --help
    - shiv-info --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/linkedin/shiv
  doc_url: https://shiv.readthedocs.io/en/latest/
  summary: A command line utility for building fully self contained Python zipapps.
  license: BSD-2-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
